### ISSUE TITLE
Refactoriser le code

### ISSUE THREAD

**Issue by metallou** [metallou/SIMPLe_graphics#11]
Comme dit le titre
Je m'en occuperai quand toutes les features présetes seront finis (je vous mets en assigned juste pour la notif)
on va essayer d'accélérer ce code

**Comment by eukavlin** [comment]
J'ai déjà factorisé une petite partie du css. Comme je m'occupe du design, je me chargerai de la factorisation complete du CSS

**Comment by metallou** [comment]
j'ai un peu factorisé le code dans le masterscript (surtout la fonction gamefunc)
@smontel tu auras surement des conflits quand tu mergeras la branche deathscreen

**Comment by bensoille** [comment]
Si en plus vous mettez des liens vers les commits en question, c'est au top :)
cf. https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
