### ISSUE TITLE
proutprout trop détaillé

### ISSUE THREAD

**Issue by metallou** [metallou/SIMPLe_graphics#16]
l'aspect des proutprout de fumée est bien trop détaillé par rapport à l'aspect pixellisé de la fusée
redessiner à la main (pixel par pixel)
rendre le dessin symétrique gauche-droite

**Comment by eukavlin** [comment]
Le sprite de fumée sera refait demain au plus tard. (modification prévue pour le 17 Dec 2016)

**Comment by eukavlin** [comment]
Proutprout modifié (branche: elise-proutprout). Branche déjà mergée sur master.
@metallou, regarde ce que tu peux faire, je trouve les proutprouts trop rapprochés. teste avec un ecart légerement plus grand si tu peux.

**Comment by eukavlin** [comment]
Quoi que non en fait, c'est bien aussi comme ça ... Donne moi ton avis, dans le doute...

**Comment by metallou** [comment]
l'espacement, ça va
par contre, je suis pas fan de la non symétrie gauche-droite (surtout le petit bout qui dépasse en haut à gauche)

**Comment by eukavlin** [comment]
Problème de symétrie réglé.
