### ISSUE TITLE
ajouter d'autres stats

### ISSUE THREAD

**Issue by metallou** [metallou/SIMPLe_graphics#17]
j'aime Lestat
(highest score, last score, average score, total score pour chaque boss + global)
last score

**Comment by eukavlin** [comment]
Pourquoi ? Les stats sont bien comme ça, non ?

**Comment by metallou** [comment]
Fait
sur metallou-stats
dans index.html, js/options.js, js/masterscript.js

**Comment by eukavlin** [comment]
Je ne suis pas fan du tout. Page de stat surchargée.

**Comment by metallou** [comment]
je m'en occupe demain

**Comment by metallou** [comment]
ayé, j'ai mis les stats sur plusieurs pages
je ferme pas l'issue tout de suite

**Comment by eukavlin** [comment]
Sauf si Sylvain a une objection au sujet de la page "stats", je pense qu'on peut clore l'issue.

**Comment by metallou** [comment]
je pensais à mettre un thead aux tables,
j'essaie ça

**Comment by eukavlin** [comment]
Pour mettre des titres à chaque table, genre "Global stats", "falling boss stats", etc ?
Parce que si c'est que ça, je pense que le thead n'est pas nécessaire, il doit y avoir une meilleure solution.

**Comment by metallou** [comment]
les theads passent nickels

**Comment by eukavlin** [comment]
Ca passe oui, y'aura juste a mettre un padding, mais je m'en charge (cf. #5 )
