### ISSUE TITLE
gifs du flyingsaucer

### ISSUE THREAD

**Issue by metallou** [metallou/SIMPLe_graphics#18]
ce serait pas mal de rendre les flammes animées (petit changement de couleur, par example)
sinon, remplacer l'extension du fichier (.gif > .png), question de cohérence (modifier dans le css)
remplacer l'extension des réacteurs (.gif > .png), question de cohérence (modifier dans le css)

**Comment by eukavlin** [comment]
Oui, ce n'était qu'une ébauche, j'avais une idée d'animation pour la flamme, mais pas au niveau des couleurs.
Je vais modifier l'extension du réacteur un peu plus tard dans l'aprem. Et pour les flammes et la soucoupe, comme c'est animé, c'est plus simple de garder le .gif
