### ISSUE TITLE
dessin boss du bas

### ISSUE THREAD

**Issue by metallou** [metallou/SIMPLe_graphics#3]
Il faut faire le dessin du boss du bas
On a pensé à un monstre type space worm (http://www.sideshowtoy.com/mas_assets/jpg/2204_press09-001.jpg)
il faudrait qu'au moins la bouche, les narines et les yeux sont visibles quand le monstre atteint la moitié de l'écran durant la partie

**Comment by eukavlin** [comment]
![spaceworm](https://cloud.githubusercontent.com/assets/23051774/21392894/4e29cf80-c792-11e6-8438-63bbe322a781.gif)

Premier dessin (taille non définitive, le dessin sera plus grand pour aller sur toute la div du boss du bas.

**Comment by metallou** [comment]
j'imaginais plus en vue du dessus (comme dans les jeux rétros)
pas une bouche gigantesque mais des tentacules et des pinces sur les cotés

**Comment by eukavlin** [comment]
Soit des tentacules soit des pinces, mais pas les deux. Ça prendrait bcp trop de temps. Mais ça je l'ai pas fait parce que du coup comme c'était censé être un "worm", un worm, c'est juste un ver, sans pinces ou tentacules... :O

**Comment by metallou** [comment]
ptet des piques alors
pas forcément un worm mais un gros monstre de l'espace

**Comment by eukavlin** [comment]
J'ai testé avec les pinces, par rapport au boss du bas et avec des avis externes, c'est mieux de garder l'espece de truc que j'ai fait plus haut.
Je vais l'enregistrer en grand format (width 2000px).
Ce sera plus simple.
