### ISSUE TITLE
dessin boss du haut

### ISSUE THREAD

**Issue by metallou** [metallou/SIMPLe_graphics#4]
Il faut faire le dessin du boss du haut
on a pensé à l'arrière d'un vaisseau, ses réacteurs et leurs flammes (inspiration wall-e: https://youtu.be/P8sUVhR7xjE?t=1m55s)
Il faut dessiner l'arrière d'un vaisseau, un réacteur de vaisseau et une flamme
visuellement, le viasseau doit apparaitre sur le réacteur qui apparait sur la flamme

**Comment by eukavlin** [comment]
Problème, j'ai essayé de mettre les backgrounds image à la soucoupe, réacteurs et flammes, mais ça donne un résultat très bizarre, comme tu as codé ces divs @metallou, problème de z-index que je n'ai pas su résoudre, si tu peux voir.
On ne peut voir que les flammes dans l'état actuel.
(branche elise-flyingsaucer)

**Comment by metallou** [comment]
c'était crade mais problème réglé
à fignoler
ps: les z-index, c'est pas génial

Le 31 décembre 2016 à 15:18, Élise Brodin <notifications@github.com> a
écrit :
