### ISSUE TITLE
ajout des crédits

### ISSUE THREAD

**Issue by metallou** [metallou/SIMPLe_graphics#6]
il faut ajouter des crédits dans la page "stats"
Pour cela, il faut remonter le bouton "return to menu" et le "<table>" des stats

**Comment by eukavlin** [comment]
Crédits rajoutés pour les avatars sur les branches "elise-credits", les liens des avatars ne sont pas encore ajoutés.
Besoin de connaitre le nom de la chanson utilisée par @smontel pour les ajouter aux crédits.

**Comment by eukavlin** [comment]
Crédits ajoutés avec noms des devs avec liens sur les pages github. Lien vers la musique fait.
